[package]
name = "snaprust"
version = "0.1.0"
authors = ["pajowu <git@ca.pajowu.de>"]

[dependencies]
alsa = "0.1.10"
clap = "*"
byteorder = "1.1.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
log = "0.3"
simplelog = "0.4"
hound = "3.1"
rodio = "0.5.2"
